[package]
name = "rust_webserver_example1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "4.0"
sqlx = { version = "0.5", features = ["runtime-async-std-rustls", "mysql"] }





